apiVersion: v1
kind: Service
metadata:
  labels:
    app: getheader
  name: getheader
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: getheader
  externalTrafficPolicy: Local
status:
  loadBalancer: {}
