
Host rg-linux-entra-demo-vm-linux-entra
	User mailadmin@eroilabdemo2.onmicrosoft.com
	HostName 74.249.155.247
	CertificateFile "/home/eroiadmin/.aadkeys/id_rsa.pub-aadcert.pub"
	IdentityFile "/home/eroiadmin/.aadkeys/id_rsa"
Host 74.249.155.247
	User mailadmin@eroilabdemo2.onmicrosoft.com
	CertificateFile "/home/eroiadmin/.aadkeys/id_rsa.pub-aadcert.pub"
	IdentityFile "/home/eroiadmin/.aadkeys/id_rsa"